# -*- coding: utf-8 -*-
"""3_energy_multiagent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZ8_weKYFwz1yof_nv5BdgwXA2bplGmU

# Energy Intelligence Platform

## Notebook 03 - Multi-Agent RAG System

Este notebook implementa una arquitectura multi-agente especializada sobre la base documental energética creada en los notebooks anteriores.

Arquitectura:

Pregunta
↓
Orchestrator Agent
↓
Agente Especializado
↓
RAG
↓
Groq
↓
Respuesta

Agentes disponibles:

- Energy Agent
- Renewables Agent
- Grid Agent
- Datacenter Agent
- AI Energy Agent
- Spain Policy Agent

Este mismo motor será posteriormente exportado a FastAPI y consumido por la aplicación web desarrollada en Lovable.

## 1. Instalaciones
"""

!pip install -q faiss-cpu
!pip install -q sentence-transformers
!pip install -q groq

!pip install sympy==1.13.1

"""## 2. Configuracion"""

from google.colab import drive

drive.mount('/content/drive')

BASE_PATH = "/content/drive/MyDrive/EnergyRag"

INDEX_PATH = f"{BASE_PATH}/energy_rag.index"
CHUNKS_PATH = f"{BASE_PATH}/energy_chunks.pkl"

"""## 3. Carga de Faiss, Chunk y Embedding"""

import faiss

index = faiss.read_index(INDEX_PATH)

print("Vectores:", index.ntotal)

import pickle

with open(CHUNKS_PATH, "rb") as f:
    chunks = pickle.load(f)

print("Chunks:", len(chunks))

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embeddings cargados")

"""## 4 Conectamos a Groq"""

import os

os.environ["GROQ_API_KEY"] = "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"

from groq import Groq

client = Groq(
    api_key=os.environ["GROQ_API_KEY"]
)

print("Groq conectado")

"""## 5. Definicion de agentes"""

AGENTS = {
    "energy": "Energy Agent",
    "renewables": "Renewables Agent",
    "grids": "Grid Agent",
    "datacenters": "Datacenter Agent",
    "ai-energy": "AI Energy Agent",
    "spain": "Spain Policy Agent"
}

AGENTS

"""## 6. Router simple v1"""

def route_question(question):

    q = question.lower()

    if any(word in q for word in [
        "spain",
        "pniec",
        "españa"
    ]):
        return "spain"

    if any(word in q for word in [
        "renewable",
        "solar",
        "wind"
    ]):
        return "renewables"

    if any(word in q for word in [
        "grid",
        "transmission",
        "electricity network"
    ]):
        return "grids"

    if any(word in q for word in [
        "data center",
        "datacenter"
    ]):
        return "datacenters"

    if any(word in q for word in [
        "ai",
        "artificial intelligence"
    ]):
        return "ai-energy"

    return "energy"

# prueba del router
tests = [
    "What are Spain renewable targets?",
    "How is AI affecting electricity demand?",
    "What are the challenges of electricity grids?",
    "How fast are data centers growing?"
]

for t in tests:
    print()
    print(t)
    print(route_question(t))

"""## 7. Busqueda especializada"""

import numpy as np

def search_by_category(
    query,
    category,
    k=5
):

    query_embedding = embedding_model.encode(
        [query]
    )

    query_embedding = np.array(
        query_embedding
    )

    distances, indices = index.search(
        query_embedding,
        50
    )

    results = []

    for idx in indices[0]:

        chunk = chunks[idx]

        if chunk["category"] == category:
            results.append(chunk)

        if len(results) >= k:
            break

    return results

#prueba
results = search_by_category(
    query="What are Spain renewable targets?",
    category="spain",
    k=3
)

for r in results:

    print("="*80)

    print(r["category"])

    print(r["source"])

    print()

    print(r["text"][:800])

"""## 8. AGENTES

### 8.1 Prompt del Spain Agent
"""

SPAIN_SYSTEM_PROMPT = """
You are a senior energy policy analyst specialized in Spain.

Use ONLY the provided context.

If the answer is not contained in the context,
say that the information is not available.

Always answer in a professional way.

Always cite the source document name.
"""

import numpy as np

def search_chunks(query, category=None, top_k=5):

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )

    distances, indices = index.search(
        np.array(query_embedding, dtype=np.float32),
        top_k * 10
    )

    results = []

    for idx in indices[0]:

        chunk = chunks[idx]

        if category is not None:
            if chunk["category"] != category:
                continue

        results.append(chunk)

        if len(results) >= top_k:
            break

    return results

def retrieve_spain_context(query, k=5):

    results = search_chunks(
        query,
        category="spain",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources

def spain_agent(question):

    context, sources = retrieve_spain_context(
        question
    )

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"system",
                "content":SPAIN_SYSTEM_PROMPT
            },
            {
                "role":"user",
                "content":f"""
Context:

{context}

Question:

{question}
"""
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

results = search_chunks(
    "renewable targets Spain",
    category="spain",
    top_k=3
)

for r in results:
    print("="*80)
    print(r["source"])
    print()
    print(r["text"][:500])

#prueba
response = spain_agent(
    "What are Spain renewable energy targets for 2030?"
)

print(response["answer"])

print("\nSources:")
print(response["sources"])

"""### 8.2 AI Energy Agent"""

AI_ENERGY_SYSTEM_PROMPT = """
You are an expert in Artificial Intelligence and Energy Systems.

Use ONLY the provided context.

Focus on:
- AI electricity demand
- AI infrastructure
- Data centers
- Grid impacts
- Energy planning

If the answer is not in the context, say so.

Always cite the source document.
"""

def retrieve_ai_energy_context(query,  k=5):

    results = search_chunks(
        query,
        category="ai-energy",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources

def ai_energy_agent(question):

    context, sources = retrieve_ai_energy_context(
        question
    )

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"system",
                "content":AI_ENERGY_SYSTEM_PROMPT
            },
            {
                "role":"user",
                "content":f"""
Context:

{context}

Question:

{question}
"""
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

response = ai_energy_agent(
    "How is AI affecting electricity demand?"
)

print(response["answer"])

print()
print(response["sources"])

"""### 8.3 Grid Agent"""

GRID_SYSTEM_PROMPT = """
You are an expert in electricity grids and power systems.

Use ONLY the provided context.

Focus on:
- transmission
- distribution
- grid modernization
- flexibility
- congestion
- grid security

If the answer is not available in the context, say so.

Always cite the source document.
"""

def retrieve_grid_context(query, k=5):

    results = search_chunks(
        query,
        category="grids",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources

def grid_agent(question):

    context, sources = retrieve_grid_context(question)

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": GRID_SYSTEM_PROMPT
            },
            {
                "role": "user",
                "content": f"""
Context:

{context}

Question:

{question}
"""
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

response = grid_agent(
    "What are the main challenges facing electricity grids?"
)

print(response["answer"])
print()
print(response["sources"])

"""### 8.4 Datacenter Agent Prompt"""

DATACENTER_SYSTEM_PROMPT = """
You are an expert in data center infrastructure and sustainability.

Use ONLY the provided context.

Focus on:
- hyperscalers
- sustainability
- electricity consumption
- carbon emissions
- cooling technologies

If the answer is not available in the context, say so.

Always cite the source document.
"""

def retrieve_datacenter_context(query, k=5):

    results = search_chunks(
        query,
        category="datacenters",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources

def datacenter_agent(question):

    context, sources = retrieve_datacenter_context(
        question
    )

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"system",
                "content":DATACENTER_SYSTEM_PROMPT
            },
            {
                "role":"user",
                "content":f"""
Context:

{context}

Question:

{question}
"""
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

response = datacenter_agent(
    "How are hyperscale data centers reducing emissions?"
)

print(response["answer"])
print()
print(response["sources"])

"""### 8.5 Renewables Agent Prompt"""

RENEWABLES_SYSTEM_PROMPT = """
You are an expert in renewable energy markets.

Use ONLY the provided context.

Focus on:
- solar
- wind
- renewable deployment
- investment trends
- renewable capacity

If the answer is not available in the context, say so.

Always cite the source document.
"""

def retrieve_renewables_context(query, k=5):

    results = search_chunks(
        query,
        category="renewables",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources

def renewables_agent(question):

    context, sources = retrieve_renewables_context(
        question
    )

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"system",
                "content":RENEWABLES_SYSTEM_PROMPT
            },
            {
                "role":"user",
                "content":f"""
Context:

{context}

Question:

{question}
"""
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

response = renewables_agent(
    "What are the main global wind market trends?"
)

print(response["answer"])
print()
print(response["sources"])

"""### 8.6 Energy Agent"""

def retrieve_energy_context(query, k=5):

    results = search_chunks(
        query,
        category="energy",
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set([r["source"] for r in results])
    )

    return context, sources

def energy_agent(question):

    context, sources = retrieve_energy_context(question)

    prompt = f"""
You are an Energy Systems Expert.

Answer ONLY using the provided context.

If the answer is not present, say:
"The information is not available in the provided context."

Context:

{context}

Question:

{question}
"""

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": sources
    }

response = energy_agent(
    "What are the main global electricity trends?"
)

print(response["answer"])

print("\nSources:")
print(response["sources"])

import inspect

print(inspect.signature(search_chunks))

"""### 8.7 Orchestrator"""

ROUTES = {
    "spain": [
        "spain",
        "pniec",
        "spanish",
        "españa",
        "renewable targets"
    ],

    "ai-energy": [
        "ai",
        "artificial intelligence",
        "data center power",
        "machine learning",
        "llm"
    ],

    "grids": [
        "grid",
        "transmission",
        "distribution",
        "interconnection",
        "electricity network"
    ],

    "datacenters": [
        "data center",
        "datacenter",
        "hyperscale",
        "cloud infrastructure"
    ],

    "renewables": [
        "solar",
        "wind",
        "renewable",
        "renewables"
    ],

    "energy": [
        "electricity",
        "energy",
        "power demand",
        "generation"
    ]
}

def classify_question(question):

    q = question.lower()

    for category, keywords in ROUTES.items():

        for keyword in keywords:

            if keyword in q:
                return category

    return "energy"

def orchestrator(question):

    route = classify_question(question)

    print(f"ROUTED TO -> {route}")

    if route == "spain":
        return spain_agent(question)

    elif route == "ai-energy":
        return ai_energy_agent(question)

    elif route == "grids":
        return grid_agent(question)

    elif route == "datacenters":
        return datacenter_agent(question)

    elif route == "renewables":
        return renewables_agent(question)

    else:
        return energy_agent(question)

response = orchestrator(
    "How is AI affecting electricity demand?"
)

print(response["answer"])

print("\nSources:")
print(response["sources"])

response = orchestrator(
    "What are the biggest electricity grid challenges?"
)

print(response["answer"])

print("\nSources:")
print(response["sources"])

"""## 9. Export to FASTAPI

El objetivo de esta sección es exportar la arquitectura multiagente validada a una API lista para producción que pueda ser utilizada por la plataforma de inteligencia energética desarrollada en Lovable.
"""

import os

PROJECT_DIR = "/content/drive/MyDrive/EnergyRag/energy_api"

os.makedirs(PROJECT_DIR, exist_ok=True)

print(PROJECT_DIR)

#creacion de carpetas
folders = [
    "agents",
    "data"
]

for folder in folders:
    os.makedirs(
        os.path.join(PROJECT_DIR, folder),
        exist_ok=True
    )

print("Folders created")

#copiar assests necesarios
import shutil

shutil.copy(
    "/content/drive/MyDrive/EnergyRag/energy_rag.index",
    f"{PROJECT_DIR}/data/energy_rag.index"
)

shutil.copy(
    "/content/drive/MyDrive/EnergyRag/energy_chunks.pkl",
    f"{PROJECT_DIR}/data/energy_chunks.pkl"
)

print("FAISS copied")

#Crear requirementes.txt
requirements = """
fastapi
uvicorn
faiss-cpu
sentence-transformers
groq
pydantic
numpy
torch
"""

with open(
    f"{PROJECT_DIR}/requirements.txt",
    "w"
) as f:
    f.write(requirements)

print("requirements.txt created")

#verificar estructura
for root, dirs, files in os.walk(PROJECT_DIR):

    level = root.replace(PROJECT_DIR, "").count(os.sep)

    indent = " " * 4 * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

"""### 9.1 Generacion de Rag.py"""

rag_code = '''
import pickle
import faiss
import numpy as np

from sentence_transformers import SentenceTransformer


INDEX_PATH = "data/energy_rag.index"
CHUNKS_PATH = "data/energy_chunks.pkl"


index = faiss.read_index(INDEX_PATH)

with open(CHUNKS_PATH, "rb") as f:
    chunks = pickle.load(f)


embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)


def search_chunks(
    query,
    category=None,
    top_k=5
):

    query_vector = embedding_model.encode(
        [query]
    )

    distances, indices = index.search(
        query_vector,
        top_k * 10
    )

    results = []

    for idx in indices[0]:

        chunk = chunks[idx]

        if category:

            if chunk["category"] != category:
                continue

        chunk["score"] = float(distances[0][0]) #mejora para los casos que no exista en los documentos cargados

        results.append(chunk)

        if len(results) >= top_k:
            break

    return results


def has_relevant_context(
    query,
    category=None,
    threshold=1.2
):

    results = search_chunks(
        query,
        category=category,
        top_k=1
    )

    if not results:
        return False

    score = results[0].get("score", 999)

    return score < threshold
'''

with open(
    f"{PROJECT_DIR}/rag.py",
    "w",
    encoding="utf-8"
) as f:

    f.write(rag_code)

print("rag.py created")

with open(
    f"{PROJECT_DIR}/rag.py",
    "r",
    encoding="utf-8"
) as f:

    print(f.read()[:1000])

import pickle
import faiss

from sentence_transformers import SentenceTransformer

INDEX_PATH = "data/energy_rag.index"
...

"""### 9.2 Generacion de agents.py"""

agents_code = '''
import os

from groq import Groq

from rag import search_chunks


client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


def build_context(query, category, k=5):

    results = search_chunks(
        query,
        category=category,
        top_k=k
    )

    context = "\n\n".join(
        [r["text"] for r in results]
    )

    sources = list(
        set(
            [r["source"] for r in results]
        )
    )

    return context, sources


def run_agent(question, category, role):

    context, sources = build_context(
        question,
        category
    )

    has_context = len(context.strip()) > 100

    if has_context:

        prompt = f"""
You are a {role}.

Answer ONLY using the provided context.

If the answer is not contained in the context,
respond exactly:

NOT_FOUND

Context:
{context}

Question:
{question}
"""

        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        answer = completion.choices[0].message.content

        if answer.strip() != "NOT_FOUND":

            return {
                "answer": answer,
                "sources": sources,
                "source_type": "rag"
            }

    fallback_prompt = f"""
You are an expert in:

- energy systems
- electricity markets
- transmission grids
- renewable energy
- data centers
- power generation

Answer professionally.

If the question is unrelated to energy,
electricity, infrastructure, data centers,
power systems or renewables, respond:

"I can only answer questions related to energy and infrastructure."

Question:
{question}
"""

    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": fallback_prompt
            }
        ],
        temperature=0.2
    )

    answer = completion.choices[0].message.content

    return {
        "answer": answer,
        "sources": [],
        "source_type": "llm"
    }

def spain_agent(question):
    return run_agent(
        question,
        "spain",
        "Spain Energy Policy Expert"
    )


def ai_energy_agent(question):
    return run_agent(
        question,
        "ai-energy",
        "AI and Energy Expert"
    )


def grid_agent(question):
    return run_agent(
        question,
        "grids",
        "Electricity Grid Expert"
    )


def datacenter_agent(question):
    return run_agent(
        question,
        "datacenters",
        "Datacenter Infrastructure Expert"
    )


def renewables_agent(question):
    return run_agent(
        question,
        "renewables",
        "Renewable Energy Expert"
    )


def energy_agent(question):
    return run_agent(
        question,
        "energy",
        "Global Energy Systems Expert"
    )

'''

with open(
    f"{PROJECT_DIR}/agents.py",
    "w",
    encoding="utf-8"
) as f:

    f.write(agents_code)

print("agents.py created")

with open(
    f"{PROJECT_DIR}/agents.py",
    "r",
    encoding="utf-8"
) as f:

    print(f.read()[:1500])

"""### 9.4 Generacion de router.py"""

router_code = '''

from agents import (
    spain_agent,
    ai_energy_agent,
    grid_agent,
    datacenter_agent,
    renewables_agent,
    energy_agent
)


ROUTES = {

    "spain": [
        "spain",
        "pniec",
        "spanish",
        "españa",
        "renewable targets"
    ],

    "ai-energy": [
        "ai",
        "artificial intelligence",
        "machine learning",
        "llm",
        "data center power"
    ],

    "grids": [
        "grid",
        "transmission",
        "distribution",
        "interconnection",
        "electricity network"
    ],

    "datacenters": [
        "data center",
        "datacenter",
        "hyperscale",
        "cloud infrastructure"
    ],

    "renewables": [
        "solar",
        "wind",
        "renewable",
        "renewables"
    ],

    "energy": [
        "electricity",
        "energy",
        "generation",
        "power demand",
        "ppa",
        "battery",
        "storage",
        "bess",
        "power plant",
        "plant",
        "utility",
        "market",
        "capacity",
        "operator",
        "iberdrola",
        "endesa",
        "enel",
        "nuclear",
        "hydrogen"
    ]

}


def classify_question(question):

    q = question.lower()

    for category, keywords in ROUTES.items():

        for keyword in keywords:

            if keyword in q:
                return category

    return "energy"


def orchestrator(question):

    route = classify_question(question)

    if route == "spain":
        result = spain_agent(question)

    elif route == "ai-energy":
        result = ai_energy_agent(question)

    elif route == "grids":
        result = grid_agent(question)

    elif route == "datacenters":
        result = datacenter_agent(question)

    elif route == "renewables":
        result = renewables_agent(question)

    else:
        result = energy_agent(question)

    result["route"] = route

    return result

'''

with open(
    f"{PROJECT_DIR}/router.py",
    "w",
    encoding="utf-8"
) as f:

    f.write(router_code)

print("router.py created")

with open(
    f"{PROJECT_DIR}/router.py",
    "r",
    encoding="utf-8"
) as f:

    print(f.read()[:1500])

"""### Generación de app.py"""

app_code = '''

from fastapi import FastAPI
from pydantic import BaseModel

from router import orchestrator


app = FastAPI(
    title="Energy Intelligence API",
    version="1.0.0"
)


class ChatRequest(BaseModel):
    question: str


@app.get("/")
def root():

    return {
        "status": "online",
        "service": "Energy Intelligence API"
    }


@app.post("/chat")
def chat(request: ChatRequest):

    result = orchestrator(
        request.question
    )

    return result


'''

with open(
    f"{PROJECT_DIR}/app.py",
    "w",
    encoding="utf-8"
) as f:

    f.write(app_code)

print("app.py created")

with open(
    f"{PROJECT_DIR}/app.py",
    "r",
    encoding="utf-8"
) as f:

    print(f.read())

for root, dirs, files in os.walk(PROJECT_DIR):

    level = root.replace(PROJECT_DIR, "").count(os.sep)

    indent = " " * 4 * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

print("""
Energy Intelligence Engine Exported

Agents:
- Spain Agent
- AI Energy Agent
- Grid Agent
- Datacenter Agent
- Renewables Agent
- Energy Agent

Components:
- FAISS Vector Store
- Sentence Transformers
- Groq LLM
- Multi-Agent Router

Status:
READY FOR FASTAPI DEPLOYMENT
""")

